import type { CodeLine,PlayerMethod } from '../../components/player/types'
export interface QuickStep{nums:number[];left:number;right:number;pivotIndex:number|null;pivotValue:number|null;i:number|null;j:number|null;phase:'target'|'pivot'|'scan'|'swap'|'settle'|'narrow'|'done';lineId:string;message:string}
export const kthMethods:PlayerMethod[]=[{id:'quickselect',label:'QuickSelect',complexity:'平均 O(N) · O(1)',languages:['javascript']}]
export const kthCode:CodeLine[]=[{id:'partition',text:'function partition(nums, left, right) {'},{id:'random',text:'  const idx = left + Math.floor(Math.random() * (right-left+1))'},{id:'pivot',text:'  const pivot = nums[idx]'},{id:'pivot-left',text:'  ;[nums[idx], nums[left]] = [nums[left], nums[idx]]'},{id:'ij',text:'  let i = left + 1, j = right'},{id:'loop',text:'  while (true) {'},{id:'scan-i',text:'    while (i <= j && nums[i] < pivot) i++'},{id:'scan-j',text:'    while (i <= j && nums[j] > pivot) j--'},{id:'break',text:'    if (i >= j) break'},{id:'swap',text:'    ;[nums[i], nums[j]] = [nums[j], nums[i]]'},{id:'move',text:'    i++; j--'},{id:'loop-close',text:'  }'},{id:'settle',text:'  ;[nums[left], nums[j]] = [nums[j], nums[left]]'},{id:'partition-return',text:'  return j'},{id:'partition-end',text:'}'},{id:'blank',text:''},{id:'main',text:'var findKthLargest = function(nums, k) {'},{id:'n',text:'  const n = nums.length'},{id:'target',text:'  const targetIndex = n - k'},{id:'bounds',text:'  let left = 0, right = n - 1'},{id:'main-loop',text:'  while (true) {'},{id:'call',text:'    const i = partition(nums, left, right)'},{id:'found',text:'    if (i === targetIndex) return nums[i]'},{id:'left-half',text:'    if (i > targetIndex) right = i - 1'},{id:'right-half',text:'    else left = i + 1'},{id:'main-close',text:'  }'},{id:'end',text:'}'}]
export const kthSteps:QuickStep[]=[
 {nums:[3,2,1,5,6,4],left:0,right:5,pivotIndex:null,pivotValue:null,i:null,j:null,phase:'target',lineId:'target',message:'n = 6，k = 2，所以目标升序下标 targetIndex = 6 - 2 = 4'},
 {nums:[4,2,1,5,6,3],left:0,right:5,pivotIndex:0,pivotValue:4,i:1,j:5,phase:'pivot',lineId:'pivot-left',message:'第一次分区随机选中值 4，并把基准交换到区间最左端'},
 {nums:[4,2,1,5,6,3],left:0,right:5,pivotIndex:0,pivotValue:4,i:3,j:5,phase:'scan',lineId:'scan-i',message:'i 跳过所有小于 4 的值，停在 5；j 停在小于 4 的值 3'},
 {nums:[4,2,1,3,6,5],left:0,right:5,pivotIndex:0,pivotValue:4,i:4,j:4,phase:'swap',lineId:'swap',message:'交换分错区间的 5 与 3，继续向中间扫描'},
 {nums:[3,2,1,4,6,5],left:0,right:5,pivotIndex:3,pivotValue:4,i:4,j:3,phase:'settle',lineId:'settle',message:'扫描交错，把基准 4 放到最终下标 3'},
 {nums:[3,2,1,4,6,5],left:4,right:5,pivotIndex:null,pivotValue:null,i:null,j:null,phase:'narrow',lineId:'right-half',message:'基准下标 3 < 目标 4，左半边全部丢弃，只搜索 [4, 5]'},
 {nums:[3,2,1,4,5,6],left:4,right:5,pivotIndex:4,pivotValue:5,i:5,j:4,phase:'settle',lineId:'partition-return',message:'第二次分区选择 5，基准最终落在下标 4'},
 {nums:[3,2,1,4,5,6],left:4,right:5,pivotIndex:4,pivotValue:5,i:null,j:null,phase:'done',lineId:'found',message:'基准下标等于 targetIndex，返回 nums[4] = 5'},
]
