import type { CodeLine, PlayerMethod } from '../../components/player/types'
export interface LruStep { operation:string; order:number[]; values:Record<number,number>; result:string; active:number|null; evicted:number|null; phase:'init'|'hit'|'miss'|'put'|'evict'|'done'; lineId:string; message:string }
export const lruMethods:PlayerMethod[]=[{id:'map-list',label:'Map + 双向链表',complexity:'O(1) · O(capacity)',languages:['javascript']}]
export const lruCode:CodeLine[]=[
 {id:'node',text:'class Node { constructor(key=0,value=0) {'},{id:'node-fields',text:'  this.key=key; this.value=value; this.prev=null; this.next=null'},{id:'node-end',text:'}}'},{id:'cache',text:'class LRUCache {'},{id:'constructor',text:'  constructor(capacity) {'},{id:'capacity',text:'    this.capacity = capacity'},{id:'dummy',text:'    this.dummy = new Node()'},{id:'circle',text:'    this.dummy.prev = this.dummy.next = this.dummy'},{id:'map',text:'    this.keyToNode = new Map()'},{id:'constructor-end',text:'  }'},{id:'get-node',text:'  #getNode(key) {'},{id:'missing',text:'    if (!this.keyToNode.has(key)) return null'},{id:'found',text:'    const node = this.keyToNode.get(key)'},{id:'promote',text:'    this.#remove(node); this.#pushFront(node)'},{id:'return-node',text:'    return node'},{id:'get-node-end',text:'  }'},{id:'get',text:'  get(key) {'},{id:'get-call',text:'    const node = this.#getNode(key)'},{id:'get-return',text:'    return node ? node.value : -1'},{id:'get-end',text:'  }'},{id:'put',text:'  put(key, value) {'},{id:'put-get',text:'    let node = this.#getNode(key)'},{id:'update',text:'    if (node) { node.value = value; return }'},{id:'new',text:'    node = new Node(key, value)'},{id:'map-set',text:'    this.keyToNode.set(key, node)'},{id:'front',text:'    this.#pushFront(node)'},{id:'over',text:'    if (this.keyToNode.size > this.capacity) {'},{id:'back',text:'      const backNode = this.dummy.prev'},{id:'delete',text:'      this.keyToNode.delete(backNode.key)'},{id:'remove-back',text:'      this.#remove(backNode)'},{id:'over-end',text:'    }'},{id:'put-end',text:'  }'},{id:'remove',text:'  #remove(x) { x.prev.next=x.next; x.next.prev=x.prev }'},{id:'push',text:'  #pushFront(x) {'},{id:'push-body',text:'    x.prev=this.dummy; x.next=this.dummy.next'},{id:'push-link',text:'    x.prev.next=x; x.next.prev=x'},{id:'push-end',text:'  }'},{id:'end',text:'}'},
]
export const lruSteps:LruStep[]=[
 {operation:'LRUCache(2)',order:[],values:{},result:'null',active:null,evicted:null,phase:'init',lineId:'constructor',message:'初始化容量为 2 的缓存；双向链表与 Map 都为空'},
 {operation:'put(1, 1)',order:[1],values:{1:1},result:'null',active:1,evicted:null,phase:'put',lineId:'front',message:'新建 key 1，写入 Map 并放到链表最前端'},
 {operation:'put(2, 2)',order:[2,1],values:{1:1,2:2},result:'null',active:2,evicted:null,phase:'put',lineId:'front',message:'key 2 成为最近使用；key 1 向 LRU 端移动'},
 {operation:'get(1)',order:[1,2],values:{1:1,2:2},result:'1',active:1,evicted:null,phase:'hit',lineId:'promote',message:'Map 命中 key 1，返回 1，并把节点 1 移到最前端'},
 {operation:'put(3, 3)',order:[3,1],values:{1:1,3:3},result:'null',active:3,evicted:2,phase:'evict',lineId:'remove-back',message:'插入 key 3 后超出容量，淘汰最久未使用的 key 2'},
 {operation:'get(2)',order:[3,1],values:{1:1,3:3},result:'-1',active:2,evicted:null,phase:'miss',lineId:'missing',message:'Map 中没有 key 2，缓存未改变，返回 -1'},
 {operation:'put(4, 4)',order:[4,3],values:{3:3,4:4},result:'null',active:4,evicted:1,phase:'evict',lineId:'delete',message:'插入 key 4 后淘汰 LRU 端的 key 1'},
 {operation:'get(1)',order:[4,3],values:{3:3,4:4},result:'-1',active:1,evicted:null,phase:'miss',lineId:'get-return',message:'key 1 已被淘汰，返回 -1'},
 {operation:'get(3)',order:[3,4],values:{3:3,4:4},result:'3',active:3,evicted:null,phase:'hit',lineId:'promote',message:'命中 key 3，返回 3，并提升到 MRU 端'},
 {operation:'get(4)',order:[4,3],values:{3:3,4:4},result:'4',active:4,evicted:null,phase:'done',lineId:'get-return',message:'命中 key 4，返回 4；最终顺序为 4（最新）→ 3（最旧）'},
]
